newsletter/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('newsletter.views',
    url(r'^(?P<pk>\d+)/$', 'detail', name='newsletter'),
    url(r'^unsubscribe/(\w+)/(.+)/$', 'unsubscribe', name='unsubscribe'),
)

newsletter/models.py
from datetime import datetime
from django.core.mail import EmailMessage
from django.db import models
from django.utils.translation import ugettext_lazy as _
from .conf import INTERNAL_USER_MODEL


class Newsletter(models.Model):
    ALL, ONLY_INTERNAL, ONLY_EXTERNAL = range(3)
    SEND_TYPES = (
        (ALL, _('all users')),  # send to internal and external subscribers
        (ONLY_INTERNAL, _('only internal')),
        (ONLY_EXTERNAL, _('only external')),
    )
    NEW, QUEUED, SENT = xrange(3)
    STATUS_CHOICES = (
        (NEW, _('New')),  # just recreated
        (QUEUED, _('Queued')),  # ready to send
        (SENT, _('Sent'))  # was sent
    )

    # select group of subscribers
    send_to = models.PositiveSmallIntegerField(
        _('send to'),
        choices=SEND_TYPES, default=ALL
    )

    # newsletter template
    template = models.CharField(
        _('template'),
        max_length=50,
        choices=(
            ('standaard', 'standaard'),
        )
    )

    # header image
    header = models.ImageField(
        _('header'),
        upload_to='uploads/newsletter/header/%Y/%m',
        blank=True
    )

    # footer image
    footer = models.ImageField(
        _('footer'),
        upload_to='uploads/newsletter/footer/%Y/%m',
        blank=True
    )

    # newsletter email message subject
    subject = models.CharField(_('subject'), max_length=200)
    intro = models.TextField(_('intro'), help_text=_('for internal use'))

    # when newsletter should be sent
    publication_date = models.DateTimeField(_('publication_date'))

    # sending status
    status = models.IntegerField(default=NEW, choices=STATUS_CHOICES)

    def __unicode__(self):
        return self.subject

    class Meta:
        ordering = ['-publication_date']
        verbose_name = _('newsletter')
        verbose_name_plural = _('newsletters')

    @models.permalink
    def get_absolute_url(self):
        return 'newsletter:newsletter', (), {'pk': self.pk}

    def render_for(self, user):
        """ render newsmail for **user** """
        from .shortcuts import render_newsletter
        return render_newsletter(self, user)

    def get_subscribers(self):
        subscribers = []

        if self.send_to == self.ONLY_EXTERNAL or\
                self.send_to == Newsletter.ALL:
            subscribers.extend(
                list(
                    ExternalSubscriber.objects.
                    filter(is_subscribed=True, email__contains="@")
                )
            )

        if INTERNAL_USER_MODEL:
            if self.send_to == self.ONLY_INTERNAL or\
                    self.send_to == Newsletter.ALL:
                subscribers.extend(
                    list(
                        INTERNAL_USER_MODEL.objects.
                        filter(is_subscribed=True, email__contains="@")
                    )
                )
        return subscribers

    @classmethod
    def get_queue(cls):
        return cls.objects.filter(
            status=Newsletter.QUEUED,
            publication_date__lt=datetime.now()
        )

    def send(self, user):
        message = self.render_for(user)
        email = EmailMessage(
            subject=self.subject,
            body=message,
            to=[user.email]
        )
        email.content_subtype = 'html'
        email.send()
        return email


class ExternalSubscriber(models.Model):
    email = models.EmailField()
    first_name = models.CharField(max_length=255, blank=True)
    last_name = models.CharField(max_length=255, blank=True)
    is_subscribed = models.BooleanField(default=True)

    class Meta:
        ordering = ('email',)
        verbose_name = _("External Subscriber")
        verbose_name_plural = _("External Subscribers")


class NewsletterItem(models.Model):
    """ Newslatter content object """
    newsletter = models.ForeignKey(Newsletter)
    order = models.IntegerField(_('order'))
    title = models.CharField(_('title'), max_length=120)
    body = models.TextField(_('body'))
    url = models.URLField(_('url'))
    url_display_name = models.CharField(
        _('url display name'),
        max_length=80,
        default="lees meer"
    )
    picture = models.ImageField(
        _('picture'),
        upload_to='uploads/newsletter/picture/%Y/%m/'
    )

    def __unicode__(self):
        return self.title

    class Meta:
        ordering = ['order']
        verbose_name = _('Newsletter item')
        verbose_name_plural = _('Newsletter items')


class NewsletterAdd(models.Model):
    """ Newslatter content add """
    newsletter = models.ForeignKey(Newsletter)
    order = models.IntegerField(_('order'))
    adds = models.ImageField(
        _('picture'),
        upload_to='uploads/newsletter/picture/%Y/%m/'
    )
    url = models.URLField(_('url'))

    def __unicode__(self):
        return self.url

    class Meta:
        ordering = ['order']
        verbose_name = _('Newsletter add')
        verbose_name_plural = _('Newsletter adds')

newsletter/forms.py
from django import forms

class ExternalSubscriberUpload(forms.Form):
    xls = forms.FileField(label = '*.xls File')

newsletter/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404

from .models import Newsletter
from .unsubscribe import unsubscribe as do_unsubscribe, InvalidCode


def detail(request, pk):
    newsletter = get_object_or_404(Newsletter, pk=pk)
    return HttpResponse(newsletter.render_for(request.user))


def unsubscribe(request, code, email):
    try:
        do_unsubscribe(code, email)
    except InvalidCode:
        return HttpResponse('Invalid code')
    return render(request, 'newsletter/unsubscribe.html', {})

newsletter/templates/newsletter/import_subscribers_form.html
{% extends "admin/object_history.html" %}
{% load i18n %}
{% block breadcrumbs %}
<div class="breadcrumbs">
    <a href="{% url admin:index %}">{% trans 'Home' %}</a> &rsaquo; 
    <a href="{% url admin:app_list 'newsletter' %}">{% trans 'Newsletter' %}</a> &rsaquo; 
    <a href="{% url admin:newsletter_externalsubscriber_changelist %}">{% trans 'External Subscriber' %}</a> &rsaquo; 
    {% trans 'Import Subscribers' %}
</div>
{% endblock %}

{% block content %}
<div id="content-main">
<div class="module">
    <form action="" method="POST" enctype="multipart/form-data">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Upload">
    </form>
</div>
</div>
{% endblock %}
<S-t_%9>

newsletter/templates/newsletter/standaard.html
{% load static from staticfiles %}
{% load i18n %}
<table width="800" border="0">
    <tr>
        <td colspan="3">
          {% if obj.header %}
            <img src="{{ SITE }}{{ obj.header.url }}" alt=''>
          {% endif %}
        </td>
    </tr>
    {% for item in obj.newsletteritem_set.all %} 
    <tr>
        <td valign="top" style="padding:0 20px 10px 20px;" width="180">
            <img src="{{ SITE }}{{ item.picture.url }}" alt="">
        </td>
        <td valign="top" style="padding:0 0 10px 0; font-family:helvetica, arial; font-size:12px;" width="400">
            <a style="padding:0; margin:0; font-size:20px; text-decoration:none; color:#52C2EA; font-weight:bold;" href="{{ item.get_absolute_url }}">{{ item.category }}</a><br>
            <a style="padding:0 0 20px 0; font-size:19px; color:#616568; text-decoration:none; font-weight:bold;" href="{{ item.url }}">{{ item.title }}</a>
            {{ item.body|linebreaks }}
            {% if item.url %}<a href="{{ item.url }}" style="color:#0EA3E3;">{{ item.url_display_name }}</a>{% endif %}
        </td>
        {% if forloop.first %}
        <td rowspan="{{ obj.newsletteritem_set.count }}" valign="top" width="200" style="padding:0 20px 10px 20px;">
            {% for add in obj.newsletteradd_set.all %}
            <a href="{{ add.url }}"><img border="0" style="border:0;" src="{{ SITE }}{{ add.adds.url }}" alt=""></a><br><br>
            {% endfor %}
        </td>
        {% endif %}
    </tr>
    <tr>
        <td colspan="2" style="padding:0 0 10px 20px;">
          <img src="{{ SITE }}{% static 'images/stippelijn.png' %}" alt="">
        </td>
    </tr>
    {% endfor %}
    <tr>
        <td colspan="3">
          {% if obj.footer %}
            <img src="{{ SITE }}{{ obj.footer.url }}" alt=''>
          {% endif %}
        </td>
    </tr>
    <tr>
        <td colspan="3">
            <p>
            {% if unsubscribe_url %}
                <a style="padding-left:20px; font-family:helvetica, arial; font-size:11px; color:#555;" href="{{ unsubscribe_url }}">{% trans "Click here to unsubscriber from newsletters" %}</a>
            {% endif %}
            </p>
        </td>
    <tr>
</table>

newsletter/templates/newsletter/unsubscribe.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Unsubscribed" %} - {{block.super}}{% endblock %}

{% block content %}
  <div class="bg-blue">
    <div class="sheet">
      <form class="subscribe subscribe-success">
      <h1 class="gray-color">
        {% trans "You will no longer recieve emails from 123feelfree" %}
      </h1>
    </div>
  </div>
{% endblock content %}